'use client';

import React from 'react';
import { useRouter } from 'next/navigation';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';

const AboutPage: React.FC = () => {
  const router = useRouter();
  
  return (
    <div className="flex flex-col min-h-screen bg-background-dark dark:bg-background-dark font-display text-slate-900 dark:text-white">
      <Navbar variant="landing" />
      
      <main className="flex-grow">
        {/* Hero */}
        <section className="py-16 md:py-24">
          <div className="container mx-auto px-4">
            <div className="flex min-h-[480px] flex-col items-center justify-center gap-6 rounded-xl bg-cover bg-center bg-no-repeat p-4 md:gap-8 overflow-hidden relative" style={{backgroundImage: 'url("https://lh3.googleusercontent.com/aida-public/AB6AXuDNXJBgNWXT-bTPNYz7hSK-k5YPA34EL_-d2LYR8lvDy4n4WtqH0Oty1X0R11Qs82yy-FZF21PYywoabzvkfr5GLoEj_mX9AMFFSlJAFBeKFdgaNrUdSq4oXltcMXpMTrOMvdNj8XLMD424u_BOCp3YCPJPtsfa6D4wVIchKSAMRhk7hZZu9YHh0EFrDflm_5iW4713vHf7PYjhnCNp34UHSjhLrIBv6lGslWFfdg3fWLIhlfNpvAzDAcpDj9zuOx9qfd5FvSDhC9EY")'}}>
              <div className="absolute inset-0 bg-black/40"></div>
              <div className="flex flex-col gap-2 text-center max-w-3xl relative z-10">
                <h1 className="text-4xl font-black leading-tight tracking-[-0.033em] text-white md:text-6xl">
                  The Future of Creativity, Generated by AI.
                </h1>
                <p className="text-base font-normal leading-normal text-white/90 md:text-lg">
                  Empowering creators with the most advanced AI image generation tools. Your vision, brought to life in seconds.
                </p>
              </div>
              <button 
                onClick={() => router.push('/generate')}
                className="relative z-10 flex min-w-[84px] max-w-[480px] cursor-pointer items-center justify-center overflow-hidden rounded-lg h-12 px-5 bg-primary text-white text-base font-bold leading-normal tracking-[0.015em] hover:bg-primary/90 transition-colors"
              >
                <span className="truncate">Try the Generator</span>
              </button>
            </div>
          </div>
        </section>

        {/* Mission */}
        <section className="py-16 md:py-24 bg-background-light dark:bg-background-dark">
          <div className="container mx-auto px-4">
            <div className="flex flex-col gap-10">
              <div className="flex flex-col gap-4 text-center items-center">
                <h2 className="text-slate-900 dark:text-white tracking-light text-3xl font-bold leading-tight md:text-4xl max-w-2xl">
                  Our Mission: Democratizing Digital Art
                </h2>
                <p className="text-slate-600 dark:text-slate-300 text-base font-normal leading-normal max-w-3xl">
                  Our goal is to make advanced AI tools for art and design accessible to everyone, from professional artists to hobbyists. We believe in empowering creativity and pushing the boundaries of what's possible.
                </p>
              </div>
              <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
                {[
                    {icon: "palette", title: "Creativity", desc: "Unlock limitless creative potential with AI that understands your vision."},
                    {icon: "lightbulb", title: "Innovation", desc: "We are constantly pushing the boundaries of generative technology."},
                    {icon: "shield", title: "Ethics", desc: "Committed to responsible AI development and fostering a positive community."}
                ].map((card, i) => (
                    <div key={i} className="flex flex-1 flex-col gap-3 rounded-xl border border-primary/20 bg-primary/10 p-4 text-center items-center">
                        <div className="text-primary"><span className="material-symbols-outlined !text-4xl">{card.icon}</span></div>
                        <div className="flex flex-col gap-1">
                            <h3 className="text-lg font-bold leading-tight text-slate-900 dark:text-white">{card.title}</h3>
                            <p className="text-sm font-normal leading-normal text-slate-600 dark:text-slate-400">{card.desc}</p>
                        </div>
                    </div>
                ))}
              </div>
            </div>
          </div>
        </section>

        {/* Team */}
        <section className="py-16 md:py-24">
            <div className="container mx-auto px-4">
                <div className="flex flex-col items-center gap-4 text-center mb-10">
                    <h2 className="text-slate-900 dark:text-white text-3xl font-bold leading-tight tracking-[-0.015em]">Meet the Team</h2>
                    <p className="text-slate-600 dark:text-slate-300 max-w-2xl">The brilliant minds behind the magic, dedicated to building the future of AI-powered creativity.</p>
                </div>
                <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-4">
                    {[
                        {name: "Alex Johnson", role: "Co-Founder & CEO", img: "https://lh3.googleusercontent.com/aida-public/AB6AXuBndPoVWqdGynNw9RW0Xe6o5GavT7SOqt9h52tgtJ7FcmfF7pFLWs54DLBQ9vrtneneRlTsUZmMj-160T_yrwBpUlt3wsU_v0Qp7KSiP93R27d4FfTFZZen7Ex0UMAM6qCaPoOSaTnep0GL8uuHMnGQNo6JPHicoY1d9Zl-e9M3-Pfj1UOUMcoJzmNuzPFE7xR-roUHI7Su3kIMMfnlhX4d18ljAhOG02o0iL_9D8QAt67K83fKoPwinC6rveHAJxMIN0T-dGMIj37N"},
                        {name: "Brenda Chen", role: "Lead AI Engineer", img: "https://lh3.googleusercontent.com/aida-public/AB6AXuDorPj8bzupu1Ti6LpaPIQuzHhEs3FMPZzaM-ciS9dJJe-q74MJp5B7XRHYhNnyEWuPXCt_hC-hm95_Hjfkl4Ov3Hnri5vQgjbkHWyODz42SmxquTuaYhxJjDYVAEkgR8tpxBtqnWlVkWMuVt4IT-1l-kyPACUtf9mVc1fek2IJTN8dSshPzEb5qT2V0hCfrZFdgAGxzrQPhYmJVpDdZ2FKhXRC9f73a44CYPn6YAi2dilqO7aajCzkn_o1KPfWfYeelWENvx6lgg_X"},
                        {name: "Chris Rodriguez", role: "Head of Design", img: "https://lh3.googleusercontent.com/aida-public/AB6AXuCQdhgGPktbbuVmiUkBWQqN_ynl2Q67Hod_POemi56MbvRY02QRK1XShJ-IhFGlwr82N7Bq37TcvfM2394_gzTj11OFNJuaVrok-Wsvez2Xojm-Nb6NyGVMsyCphk0K3OyF0Ssch6Xkib5tnDxRVyHScNVryDFWheWHLpvymwS3smbueC0I_7H29KDiWe2Lzk7W2zQooQmeFpoZLReeoHszbiujxcIyVNN5JwJkPt5BDqDafnsDeA7Cz1t25prVkWdqeXY8T649Z5Ov"},
                        {name: "Dana Williams", role: "Community Manager", img: "https://lh3.googleusercontent.com/aida-public/AB6AXuAEVIcN3WicZjX6V4EJhUHNmq1-gH1tB7gziTnAZmfGwHM6TNohV6G_dA7EuMGXX4lGGieToSH-U5eonTC3b2XJCKwKCZf73meG-IqMVEYL487KCOptAhlU3QXcqRpT1HrWRD1ih3JhNzgx-82k6ssgnliLgFWWRkITTKeaeQ0uM277wvZVNfnY-ClyPkIfMLQYi_-t91OB612BbHPKT0NsFc1PIrHEFNLGbZm-3G7aBAuiaN5Hf4Tlx8Jf44QAa7My4aEyMlejhbqt"}
                    ].map((member, i) => (
                        <div key={i} className="flex flex-col gap-3 text-center pb-3">
                            <div className="px-4">
                                <div className="w-full rounded-full bg-cover bg-center bg-no-repeat aspect-square border-2 border-primary/20" style={{backgroundImage: `url("${member.img}")`}}></div>
                            </div>
                            <div>
                                <p className="text-base font-medium leading-normal text-slate-900 dark:text-white">{member.name}</p>
                                <p className="text-sm font-normal leading-normal text-slate-600 dark:text-slate-400">{member.role}</p>
                            </div>
                        </div>
                    ))}
                </div>
            </div>
        </section>

        {/* Tech */}
        <section className="py-16 md:py-24 bg-primary/10">
            <div className="container mx-auto px-4">
                <div className="flex flex-col lg:flex-row items-center gap-10 lg:gap-16">
                    <div className="w-full lg:w-1/2 flex flex-col gap-4 text-center lg:text-left">
                        <h2 className="text-3xl font-bold tracking-tight text-slate-900 dark:text-white">The Technology Behind the Magic</h2>
                        <p className="text-slate-600 dark:text-slate-300">We leverage state-of-the-art diffusion models, a revolutionary class of machine learning technology. These models learn to reverse a process of adding noise to an image, allowing them to generate incredibly detailed and coherent visuals from simple text descriptions.</p>
                    </div>
                    <div className="w-full lg:w-1/2">
                        <div className="flex flex-col items-center justify-center gap-4 md:flex-row lg:flex-col xl:flex-row">
                            <div className="flex-1 flex flex-col items-center text-center gap-2 p-4 rounded-lg bg-background-light dark:bg-background-dark/50">
                                <span className="material-symbols-outlined text-primary !text-4xl">edit</span>
                                <p className="font-bold text-slate-900 dark:text-white">Text Prompt</p>
                            </div>
                            <div className="text-primary transform rotate-90 md:rotate-0"><span className="material-symbols-outlined !text-4xl">arrow_right_alt</span></div>
                            <div className="flex-1 flex flex-col items-center text-center gap-2 p-4 rounded-lg bg-background-light dark:bg-background-dark/50">
                                <span className="material-symbols-outlined text-primary !text-4xl">memory</span>
                                <p className="font-bold text-slate-900 dark:text-white">AI Model</p>
                            </div>
                            <div className="text-primary transform rotate-90 md:rotate-0"><span className="material-symbols-outlined !text-4xl">arrow_right_alt</span></div>
                            <div className="flex-1 flex flex-col items-center text-center gap-2 p-4 rounded-lg bg-background-light dark:bg-background-dark/50">
                                <span className="material-symbols-outlined text-primary !text-4xl">image</span>
                                <p className="font-bold text-slate-900 dark:text-white">Image Output</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        {/* CTA */}
        <section className="py-16 md:py-24">
            <div className="container mx-auto px-4">
                <div className="flex flex-col items-center justify-center gap-6 rounded-xl bg-primary/90 p-10 text-center">
                    <h2 className="text-3xl font-bold leading-tight tracking-[-0.033em] text-white">Join Us On Our Journey</h2>
                    <p className="max-w-xl text-base font-normal leading-normal text-white/80">Ready to bring your ideas to life? Start creating with the most powerful and intuitive AI image generator today.</p>
                    <button 
                        onClick={() => router.push('/signup')}
                        className="flex min-w-[84px] cursor-pointer items-center justify-center overflow-hidden rounded-lg h-12 px-5 bg-white text-primary text-base font-bold leading-normal tracking-[0.015em] hover:bg-slate-200 transition-colors"
                    >
                        <span className="truncate">Start Creating for Free</span>
                    </button>
                </div>
            </div>
        </section>
      </main>
      
      <Footer />
    </div>
  );
};

export default AboutPage;